/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import baseDeDonnee.metier.Match;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author cleme
 */
public class JourCalendar extends javax.swing.JPanel {

    private boolean modifiable;
    private CalendarView winMere;
    public void actuMatch()
    {
        try {
            winMere.RefreshDate();
        } catch (SQLException ex) {
            Logger.getLogger(JourCalendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void modifActionPerformed(java.awt.event.ActionEvent evt, Match m) {                                       
        Modifier c = new Modifier(m, this);
        c.setVisible(true);
    }
    /**
     * Creates new form Calendar
     * @param jour
     * @param jourSemaine
     * @param listMatch
     */
    public JourCalendar(Integer jour, String jourSemaine, ArrayList<Match> listMatch, CalendarView win, boolean modif) {
        modifiable = modif;
        winMere = win;
        initComponents();
        if(jour < 10){
            lblJour.setText("0" + String.valueOf(jour));
        } else {
            lblJour.setText(String.valueOf(jour));
        }
        
        lblJourSemaine.setText("(" + jourSemaine + ")");
        
        for(Match m : listMatch){
            AfficherMatch(m);
        }
        
        panelMatch.revalidate();
        panelMatch.repaint();
    }

    public void AfficherMatch(Match m){
        JButton btn = new JButton();
        
        //Score du match
        String score;
        if(m.getScore() == null){
            score = "Pas joué";
        } else {
            score = "Score : " + m.getScore().getS1() + " / " + m.getScore().getS2();
        }
        
        //Heure du match
        String heureMatch;
        if(m.getDate().get(GregorianCalendar.HOUR) < 10) {
            heureMatch = "0" + String.valueOf(m.getDate().get(GregorianCalendar.HOUR)) + ":";
        } else {
            heureMatch = String.valueOf(m.getDate().get(GregorianCalendar.HOUR)) + ":";
        }
        if(m.getDate().get(GregorianCalendar.MINUTE) < 10) {
            heureMatch += "0" + String.valueOf(m.getDate().get(GregorianCalendar.MINUTE));
        } else {
            heureMatch += String.valueOf(m.getDate().get(GregorianCalendar.MINUTE));
        }
        String txt = "<html><div style='text-align:center;'>" + m.getParticipant1().getNom() + " / " + m.getParticipant2().getNom() + "<br/>à " + heureMatch + "<br />" + score + "<div></html>\"";
        btn.setText(txt);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);
        btn.setSize(150, 60);
        btn.setPreferredSize(new Dimension(150, 60));
        
        if (modifiable)
        {
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt, m);
            }
        });
        }
        panelMatch.add(btn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJour = new javax.swing.JLabel();
        lblJourSemaine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMatch = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(900, 75));
        setMinimumSize(new java.awt.Dimension(900, 75));
        setPreferredSize(new java.awt.Dimension(900, 75));

        lblJour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJour.setText("01");

        lblJourSemaine.setText("(Lundi)");
        lblJourSemaine.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(40, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(40, 10));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        panelMatch.setBackground(new java.awt.Color(255, 255, 255));
        panelMatch.setPreferredSize(new java.awt.Dimension(732, 55));
        panelMatch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 3));
        jScrollPane1.setViewportView(panelMatch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJour)
                .addGap(2, 2, 2)
                .addComponent(lblJourSemaine, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJour, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(lblJourSemaine))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJour;
    private javax.swing.JLabel lblJourSemaine;
    private javax.swing.JPanel panelMatch;
    // End of variables declaration//GEN-END:variables
}
